'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Check, CircleUserRound, Compass, Flag, Languages, LayoutDashboard, Menu, Plus, RefreshCw, Settings, Sparkles, Target, X } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Locale = 'uz' | 'en' | 'ru';
const copy = {
  uz: { greeting:'Xayrli tong, Aziz', subtitle:'Bugun hayotingizni bir qadam oldinga olib boring.', today:'Bugun', life:'Hayotim', goals:'Maqsadlar', reviews:'Tahlillar', settings:'Sozlamalar', overview:'Bugungi ko‘rinish', focus:'Asosiy e’tibor', focusText:'Sog‘liq sohasini 6 dan 7 ga olib chiqish', next:'Keyingi qadam', walk:'30 daqiqa piyoda yuring', due:'Bugun, 18:00', done:'Bajarildi', wheel:'Hayot g‘ildiragi', wheelHint:'Har bir sohani 1 dan 10 gacha baholang.', update:'Baholashni yangilash', progress:'Faol maqsadlar', allGoals:'Barcha maqsadlar', years:'5 yillik', review:'Keyingi oylik tahlil', reviewDate:'1 sentabr', start:'Tahlilni boshlash', add:'Maqsad qo‘shish', health:'Sog‘liq', career:'Kasb', finance:'Moliya', relations:'Munosabatlar', family:'Oila', growth:'Rivojlanish', fun:'Hordiq', environment:'Muhit' },
  en: { greeting:'Good morning, Aziz', subtitle:'Move your life one intentional step forward today.', today:'Today', life:'My Life', goals:'Goals', reviews:'Reviews', settings:'Settings', overview:'Today at a glance', focus:'Priority focus', focusText:'Move Health from a 6 to a 7', next:'Next action', walk:'Take a 30-minute walk', due:'Today, 18:00', done:'Complete', wheel:'Wheel of Life', wheelHint:'Rate each area from 1 to 10.', update:'Update assessment', progress:'Active goals', allGoals:'View all goals', years:'5-year', review:'Next monthly review', reviewDate:'September 1', start:'Start review', add:'Add goal', health:'Health', career:'Career', finance:'Finances', relations:'Relationships', family:'Family', growth:'Growth', fun:'Recreation', environment:'Environment' },
  ru: { greeting:'Доброе утро, Азиз', subtitle:'Сделайте сегодня один осознанный шаг вперёд.', today:'Сегодня', life:'Моя жизнь', goals:'Цели', reviews:'Обзоры', settings:'Настройки', overview:'Сегодняшний обзор', focus:'Главный фокус', focusText:'Повысить «Здоровье» с 6 до 7', next:'Следующее действие', walk:'Прогуляться 30 минут', due:'Сегодня, 18:00', done:'Выполнить', wheel:'Колесо жизни', wheelHint:'Оцените каждую сферу от 1 до 10.', update:'Обновить оценку', progress:'Активные цели', allGoals:'Все цели', years:'5 лет', review:'Следующий месячный обзор', reviewDate:'1 сентября', start:'Начать обзор', add:'Добавить цель', health:'Здоровье', career:'Карьера', finance:'Финансы', relations:'Отношения', family:'Семья', growth:'Развитие', fun:'Отдых', environment:'Окружение' },
};
const initialScores = [6,7,5,8,7,6,4,7];
const colors = ['#e26552','#5b7fbd','#e2a849','#b56797','#4b9a8c','#7768b6','#d47b43','#60946b'];

function LifeWheel({ labels, scores }: { labels:string[]; scores:number[] }) {
  const size=310, center=size/2, radius=104;
  const point=(index:number,value:number)=>{ const angle=(Math.PI*2*index)/scores.length-Math.PI/2; const r=radius*(value/10); return [center+Math.cos(angle)*r,center+Math.sin(angle)*r]; };
  const polygon=scores.map((value,index)=>point(index,value).join(',')).join(' ');
  return <div className="relative mx-auto aspect-square w-full max-w-[310px]" aria-label={labels.map((l,i)=>`${l}: ${scores[i]}/10`).join(', ')}>
    <svg viewBox={`0 0 ${size} ${size}`} className="h-full w-full overflow-visible" role="img">
      {[2,4,6,8,10].map(level=><polygon key={level} points={scores.map((_,i)=>point(i,level).join(',')).join(' ')} fill="none" stroke="#dfe5df" strokeWidth="1" />)}
      {scores.map((_,i)=>{const [x,y]=point(i,10); return <line key={i} x1={center} y1={center} x2={x} y2={y} stroke="#e6eae6" />})}
      <polygon points={polygon} fill="#2f776a" fillOpacity=".18" stroke="#2f776a" strokeWidth="2.5" />
      {scores.map((value,i)=>{const [x,y]=point(i,value); return <circle key={i} cx={x} cy={y} r="4" fill={colors[i]} stroke="white" strokeWidth="2" />})}
    </svg>
    {labels.map((label,i)=>{const angle=(Math.PI*2*i)/labels.length-Math.PI/2; const x=50+Math.cos(angle)*45, y=50+Math.sin(angle)*45; return <span key={label} className="pointer-events-none absolute -translate-x-1/2 -translate-y-1/2 whitespace-nowrap text-[10px] font-semibold text-slate-500" style={{left:`${x}%`,top:`${y}%`}}>{label}</span>})}
  </div>;
}

export default function Home() {
  const [locale,setLocale]=useState<Locale>('uz'); const [scores,setScores]=useState(initialScores); const [completed,setCompleted]=useState(false); const [mobileNav,setMobileNav]=useState(false);
  const t=copy[locale]; const labels=useMemo(()=>[t.health,t.career,t.finance,t.relations,t.family,t.growth,t.fun,t.environment],[t]);
  const nav=[[t.today,LayoutDashboard],[t.life,Compass],[t.goals,Target],[t.reviews,RefreshCw]] as const;
  const goals = [
    [t.career, locale==='ru'?'Стать руководителем продукта':locale==='en'?'Become a product leader':'Product rahbari bo‘lish',64,'2029','#5b7fbd'],
    [t.finance, locale==='ru'?'Создать финансовую подушку':locale==='en'?'Build a financial safety net':'Moliyaviy zaxira yaratish',42,'2028','#e2a849'],
    [t.growth, locale==='ru'?'Свободно говорить по-английски':locale==='en'?'Speak English confidently':'Ingliz tilida erkin gapirish',78,'2027','#7768b6'],
  ];
  return <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><div className="mx-auto grid min-h-screen max-w-[1580px] lg:grid-cols-[248px_1fr]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[248px] flex-col border-r border-slate-200 bg-[#f8faf7] p-5 transition-transform lg:sticky lg:translate-x-0 ${mobileNav?'translate-x-0':'-translate-x-full'}`}>
      <div className="mb-9 flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-[14px] bg-[#2f776a] text-white"><Sparkles size={19}/></div><div><p className="font-heading text-lg font-bold leading-none">Muvozanat</p><p className="mt-1 text-[10px] font-medium uppercase tracking-[.18em] text-slate-400">Life, intentionally</p></div></div><button onClick={()=>setMobileNav(false)} className="lg:hidden" aria-label="Close menu"><X/></button></div>
      <nav className="space-y-1">{nav.map(([label,Icon],i)=><button key={label} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${i===0?'bg-white text-[#25685d] shadow-sm ring-1 ring-slate-200/80':'text-slate-500 hover:bg-white/70 hover:text-slate-800'}`}><Icon size={18}/>{label}</button>)}</nav>
      <div className="mt-auto space-y-1 border-t border-slate-200 pt-4"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-500"><Settings size={18}/>{t.settings}</button><div className="flex items-center gap-3 rounded-xl px-3 py-3"><div className="grid size-9 place-items-center rounded-full bg-[#e7bda5] text-sm font-bold text-[#693f2c]">AZ</div><div className="min-w-0"><p className="truncate text-sm font-semibold">Aziz Karimov</p><p className="truncate text-xs text-slate-400">aziz@example.uz</p></div></div></div>
    </aside>
    <section className="min-w-0"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-200/80 bg-white/85 px-5 backdrop-blur-xl md:px-10"><button onClick={()=>setMobileNav(true)} className="rounded-xl border border-slate-200 p-2 lg:hidden" aria-label="Open menu"><Menu size={20}/></button><div className="hidden md:block"><p className="text-sm font-semibold text-slate-500">{t.today} · 29 Aug</p></div><div className="ml-auto flex items-center gap-2"><Languages size={17} className="text-slate-400"/><label className="sr-only" htmlFor="locale">Language</label><select id="locale" value={locale} onChange={e=>setLocale(e.target.value as Locale)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold outline-none focus:ring-2 focus:ring-[#2f776a]/30"><option value="uz">O‘zbekcha</option><option value="en">English</option><option value="ru">Русский</option></select><button className="ml-1 grid size-10 place-items-center rounded-full bg-[#f0f3ef] text-slate-500" aria-label="Profile"><CircleUserRound size={20}/></button></div></header>
      <div className="mx-auto max-w-[1240px] px-5 py-8 md:px-10 md:py-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-[#c56d50]">{t.overview}</p><h1 className="font-heading text-3xl font-bold tracking-[-.035em] md:text-[42px]">{t.greeting}</h1><p className="mt-2 text-sm text-slate-500 md:text-base">{t.subtitle}</p></div><Button className="h-11 rounded-xl bg-[#2f776a] px-4 shadow-lg shadow-emerald-900/10 hover:bg-[#235f55]"><Plus/>{t.add}</Button></div>
        <div className="grid gap-5 xl:grid-cols-[1.35fr_.85fr]"><section className="overflow-hidden rounded-[24px] border border-[#dfe5df] bg-white shadow-[0_12px_40px_rgba(35,65,57,.06)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-heading text-xl font-bold">{t.wheel}</h2><p className="mt-1 text-xs text-slate-400">{t.wheelHint}</p></div><button className="rounded-xl bg-[#f2f6f3] p-2.5 text-[#2f776a]" aria-label={t.update}><RefreshCw size={17}/></button></div><div className="grid items-center gap-4 p-5 md:grid-cols-[1fr_1fr] md:p-7"><LifeWheel labels={labels} scores={scores}/><div className="grid grid-cols-2 gap-x-5 gap-y-3">{labels.map((label,i)=><label key={label} className="group"><span className="mb-1.5 flex items-center justify-between text-[11px] font-semibold text-slate-500"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full" style={{background:colors[i]}}/>{label}</span><b className="text-slate-800">{scores[i]}</b></span><input type="range" min="1" max="10" value={scores[i]} onChange={e=>setScores(scores.map((s,index)=>index===i?Number(e.target.value):s))} className="h-1.5 w-full cursor-pointer accent-[#2f776a]"/></label>)}<Button variant="outline" className="col-span-2 mt-2 h-10 rounded-xl border-[#cfd9d2] text-[#2f776a]" onClick={()=>setScores(scores.map((s,i)=>i===0?Math.min(10,s+1):s))}>{t.update}<ArrowRight/></Button></div></div></section>
          <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-1"><section className="rounded-[24px] bg-[#244f48] p-6 text-white shadow-[0_16px_45px_rgba(32,72,64,.2)]"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-100/70">{t.focus}</p><Flag size={17} className="text-[#f0a27f]"/></div><h2 className="mt-4 max-w-[330px] font-heading text-2xl font-bold leading-tight">{t.focusText}</h2><div className="mt-6 rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-emerald-50/60">{t.next}</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>setCompleted(!completed)} className={`grid size-9 shrink-0 place-items-center rounded-full border transition ${completed?'border-[#efad8f] bg-[#efad8f] text-[#244f48]':'border-white/30 hover:bg-white/10'}`} aria-label={t.done}>{completed&&<Check size={18}/>}</button><div><p className={`text-sm font-semibold ${completed?'line-through opacity-60':''}`}>{t.walk}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-emerald-50/60"><CalendarDays size={12}/>{t.due}</p></div></div></div></section><section className="rounded-[24px] border border-[#eadfd7] bg-[#fff8f3] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#bc6d4f]">{t.review}</p><h2 className="mt-3 font-heading text-2xl font-bold">{t.reviewDate}</h2></div><div className="grid size-11 place-items-center rounded-2xl bg-[#f3d8c7] text-[#a8583c]"><CalendarDays size={20}/></div></div><Button variant="outline" className="mt-6 h-10 w-full rounded-xl border-[#e7cbbb] bg-white/70 text-[#a8583c]">{t.start}<ArrowRight/></Button></section></div></div>
        <section className="mt-6 rounded-[24px] border border-slate-200 bg-white p-6 shadow-[0_12px_35px_rgba(35,65,57,.04)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-xl font-bold">{t.progress}</h2><p className="mt-1 text-xs text-slate-400">3 {t.goals.toLowerCase()}</p></div><button className="flex items-center gap-1 text-sm font-semibold text-[#2f776a]">{t.allGoals}<ArrowRight size={15}/></button></div><div className="grid gap-4 md:grid-cols-3">{goals.map(([area,title,progress,year,color])=><article key={String(title)} className="rounded-2xl border border-slate-100 bg-[#fbfcfb] p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className="rounded-full px-2.5 py-1 text-[10px] font-bold" style={{background:`${color}18`,color:String(color)}}>{area}</span><span className="text-xs font-semibold text-slate-400">{t.years}</span></div><h3 className="mt-4 min-h-12 font-heading text-base font-bold leading-snug">{title}</h3><div className="mt-5 flex items-center justify-between text-xs"><span className="font-semibold text-slate-500">{year}</span><b>{progress}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{width:`${progress}%`,background:String(color)}}/></div></article>)}</div></section>
      </div>
    </section>
  </div></main>;
}
